name: docdigital_app
description: DocDigital mobile application
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.2.5

  cupertino_icons: ^1.0.8
  http: ^1.2.0

  file_picker: ^8.0.0

  flutter_secure_storage: ^9.0.0

  flutter_localizations:
    sdk: flutter

  syncfusion_flutter_pdfviewer: ^32.2.8

  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo_docdigital.png
    - assets/images/cadeado.png
